---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: python
        image: python
        command: ["/opt/bin/count.sh"]
        volumeMounts:
        - name: init-script
          mountPath: /opt/bin/count.sh
          subPath: count.sh
        - name: count-script
          mountPath: /var/lib/www/count
          subPath: count.py
      volumes:
      - name: init-script
        configMap:
          name: init-script
          defaultMode: 0755
      - name: count-script
        configMap:
          name: count-script
          defaultMode: 0755
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: python
        image: python
        command: ["/opt/bin/reset.sh"]
        volumeMounts:
        - name: init-script
          mountPath: /opt/bin/reset.sh
          subPath: reset.sh
        - name: reset-script
          mountPath: /var/lib/www/reset
          subPath: reset.py
      volumes:
      - name: init-script
        configMap:
          name: init-script
          defaultMode: 0755
      - name: reset-script
        configMap:
          name: reset-script
          defaultMode: 0755
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  serviceName: "redis"
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        command: ["redis-server"]
        args: ["--save", "60", "1", "--loglevel", "warning"]
        volumeMounts:
        - name: redis-volume
          mountPath: /data
      terminationGracePeriodSeconds: 0
  volumeClaimTemplates:
  - metadata:
      name: redis-volume
    spec:
      storageClassName: longhorn
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 100Mi
