---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: python
        image: python:slim
        command: ["/bin/sh", "-c"]
        args:
          - pip install --upgrade pip;
            pip install redis;
            /var/www/count;
        volumeMounts:
        - name: pip-local
          mountPath: /var/www/.local
        - name: pip-cache
          mountPath: /var/www/.cache
        - name: count-script
          mountPath: /var/www/count
          subPath: count.py
      securityContext:
        runAsUser: 33
        runAsGroup: 33
      volumes:
      - name: pip-local
        emptyDir:
          sizeLimit: 100Mi
      - name: pip-cache
        emptyDir:
          sizeLimit: 100Mi
      - name: count-script
        configMap:
          name: count-script
          defaultMode: 0755
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: python
        image: python:slim
        command: ["/bin/sh", "-c"]
        args:
          - pip install --upgrade pip;
            pip install redis;
            /var/www/reset;
        volumeMounts:
        - name: pip-local
          mountPath: /var/www/.local
        - name: pip-cache
          mountPath: /var/www/.cache
        - name: reset-script
          mountPath: /var/www/reset
          subPath: reset.py
      securityContext:
        runAsUser: 33
        runAsGroup: 33
      volumes:
      - name: pip-local
        emptyDir:
          sizeLimit: 100Mi
      - name: pip-cache
        emptyDir:
          sizeLimit: 100Mi
      - name: reset-script
        configMap:
          name: reset-script
          defaultMode: 0755
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  serviceName: "redis"
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        command: ["redis-server"]
        args: ["--save", "60", "1", "--loglevel", "warning"]
        volumeMounts:
        - name: redis-volume
          mountPath: /data
      terminationGracePeriodSeconds: 0
  volumeClaimTemplates:
  - metadata:
      name: redis-volume
    spec:
      storageClassName: longhorn
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 100Mi
