---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: page-counter
spec:
  ingressClassName: haproxy
  rules:
    - host: "count.example.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
    - host: "reset.example.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
