---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: page-counter
  annotations:
    haproxy.org/path-rewrite: (.*) /cgi-bin/\1.py
spec:
  ingressClassName: haproxy
  rules:
    - host: "example.com"
      http:
        paths:
          - path: /count
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /reset
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
