---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: page-counter
spec:
  ingressClassName: haproxy
  rules:
    - host: "www2.unixworld.io"
      http:
        paths:
          - path: /count
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /reset
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
  tls:
  - hosts:
    - www2.unixworld.io
    secretName: www2-cert
